# ESLint config
# http://eslint.org/docs/user-guide/configuring
# https://github.com/JS-DevTools/eslint-config-modular

root: true

extends:
  - modular/best-practices
  - modular/style
  - modular/es6
  - modular/node
