language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
before_install:
  - npm update -g npm   # update npm to a version that supports peerDependencies
after_success:
  - cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
