# Travis CI config
# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/

sudo: false
language: node_js
node_js:
  - '0.10'
  - '0.11'
  - '0.12'
after_success:
  - cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
