# Travis CI config
# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/

sudo: false
language: node_js
matrix:
  include:
    - node_js: 0.10
    - node_js: 0.11
    - node_js: 0.12
    - node_js: 4
    - node_js: 5
branches:
  only:
    - master            # only run CI on the master branch
    - /^PR /            # also build pull requests
after_success:
  - cat coverage/*/lcov.info > coveralls.txt                    # concatenate all code-coverage data into a single file
  - cat coveralls.txt                                           # output the file contents (for debugging)
  - ls -R1 coverage/*/lcov.info                                 # list the files (for debugging)
  - cat coveralls.txt | node_modules/coveralls/bin/coveralls.js # send code-coverage data to Coveralls
