remote_theme: APIDevTools/gh-pages-theme

title: Swagger Express Middleware
logo: http://apidevtools.org/img/logos/logo.png

author:
  twitter: APIDevTools

google_analytics: UA-68102273-2

twitter:
  username: APIDevTools
  card: summary

defaults:
  - scope:
      path: ""
    values:
      image: http://apidevtools.org/img/logos/card.png

  - scope:
      path: "test/**/*"
    values:
      sitemap: false

  - scope:
      path: "samples/index.html"
    values:
      sitemap: false

plugins:
  - jekyll-sitemap
